package com.mycompany.projectresto;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Win10
 */
import java.io.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        RF1 = new javax.swing.JRadioButton();
        SRF1 = new javax.swing.JRadioButton();
        RCF1 = new javax.swing.JRadioButton();
        RCF2 = new javax.swing.JRadioButton();
        CHE2 = new javax.swing.JRadioButton();
        CHE1 = new javax.swing.JRadioButton();
        HAMF = new javax.swing.JRadioButton();
        HAM1 = new javax.swing.JRadioButton();
        PIE = new javax.swing.JRadioButton();
        CHOCO = new javax.swing.JRadioButton();
        SPRITE = new javax.swing.JRadioButton();
        COLA = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane3 = new javax.swing.JTextPane();
        jButton4 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 500));

        jPanel2.setBackground(new java.awt.Color(255, 102, 102));

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Win10\\Downloads\\623df7ec99b01af289938c58e17e5480.png")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(244, 244, 244))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        jLabel2.setText("Burger Meal");

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        jLabel3.setText("Chicken Meal");

        jLabel4.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        jLabel4.setText("Drinks & Desserts");

        RF1.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        RF1.setText("Regular Fried Chicken w/ Rice");
        RF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RF1ActionPerformed(evt);
            }
        });

        SRF1.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        SRF1.setText("Spicy Fried Chicken w/ Rice");
        SRF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SRF1ActionPerformed(evt);
            }
        });

        RCF1.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        RCF1.setText("Regular Chicken Fillet w/ Rice");
        RCF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RCF1ActionPerformed(evt);
            }
        });

        RCF2.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        RCF2.setText("Chicken Fillet Ala King w/ Rice");

        CHE2.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        CHE2.setText("Cheeseburger w/ Fries");

        CHE1.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        CHE1.setText("Cheeseburger");
        CHE1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CHE1ActionPerformed(evt);
            }
        });

        HAMF.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        HAMF.setText("Hamburger w/ Fries");

        HAM1.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        HAM1.setText("Hamburger");

        PIE.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        PIE.setText("Apple Pie");

        CHOCO.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        CHOCO.setText("Chocofloat");

        SPRITE.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        SPRITE.setText("Sprite");

        COLA.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        COLA.setText("Cola-cola");

        jButton1.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        jButton1.setText("ENTER");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        jButton2.setText("CLEAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        jButton3.setText("EXIT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setText("Subtotal");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setText("Tax");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel7.setText("Total");

        jScrollPane1.setViewportView(jTextPane1);

        jScrollPane2.setViewportView(jTextPane2);

        jScrollPane3.setViewportView(jTextPane3);

        jButton4.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        jButton4.setText("SAVE ORDER TO DATABASE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Subtotal", "Tax", "Grandtotal"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTable1);

        btnAdd.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        btnAdd.setText("CREATE ORDER");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        jButton5.setText("UPDATE ORDER");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        jButton6.setText("DELETE ORDER");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RCF2)
                            .addComponent(RCF1)
                            .addComponent(SRF1)
                            .addComponent(RF1)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(CHE2)
                            .addComponent(CHE1)
                            .addComponent(HAMF)
                            .addComponent(HAM1))
                        .addGap(160, 160, 160)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PIE)
                            .addComponent(CHOCO)
                            .addComponent(SPRITE)
                            .addComponent(COLA)
                            .addComponent(jLabel4)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(19, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(61, 61, 61))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(12, 12, 12)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)))
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE))))
                .addGap(27, 27, 27))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel4)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(HAM1)
                        .addGap(18, 18, 18)
                        .addComponent(HAMF)
                        .addGap(18, 18, 18)
                        .addComponent(CHE1)
                        .addGap(18, 18, 18)
                        .addComponent(CHE2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(RF1)
                        .addGap(18, 18, 18)
                        .addComponent(SRF1)
                        .addGap(18, 18, 18)
                        .addComponent(RCF1)
                        .addGap(18, 18, 18)
                        .addComponent(RCF2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(COLA)
                        .addGap(18, 18, 18)
                        .addComponent(SPRITE)
                        .addGap(18, 18, 18)
                        .addComponent(CHOCO)
                        .addGap(18, 18, 18)
                        .addComponent(PIE)))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)
                            .addComponent(jButton3)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAdd)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5)
                        .addGap(18, 18, 18)
                        .addComponent(jButton6)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SRF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SRF1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SRF1ActionPerformed

    private void RCF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RCF1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RCF1ActionPerformed

    private void CHE1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CHE1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CHE1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        double total;
        double subtotal = 0;
        final double TAXRATE = .04;
        double tax;
        
        //Chicken Meals
        if (RF1.isSelected()){
            subtotal = subtotal + 113;
        }
        if (SRF1.isSelected()){
            subtotal = subtotal + 113;
        }
        if (RCF1.isSelected()){
            subtotal = subtotal + 68;
        }
        if (RCF2.isSelected()){
            subtotal = subtotal + 73;
        }
        if (SRF1.isSelected()){
            subtotal = subtotal + 113;
        }
        
        //Burger Meals
        if (HAM1.isSelected()){
            subtotal = subtotal + 28;
        }
        if (HAMF.isSelected()){
            subtotal = subtotal + 43;
        }
        if (CHE1.isSelected()){
            subtotal = subtotal + 38;
        }
        if (CHE2.isSelected()){
            subtotal = subtotal + 63;
        }
        
        //Drinks & Desserts
        if (COLA.isSelected()){
            subtotal = subtotal + 18;
        }
        if (SPRITE.isSelected()){
            subtotal = subtotal + 18;
        }
        if (CHOCO.isSelected()){
            subtotal = subtotal + 33;
        }
        if (PIE.isSelected()){
            subtotal = subtotal + 28;
        }
        
        jTextPane1.setText(Double.toString(subtotal));
        
        subtotal = Double.parseDouble(jTextPane1.getText());
        tax = subtotal * TAXRATE;
        total = tax + subtotal;
        
        jTextPane2.setText(Double.toString(tax));
        jTextPane3.setText(Double.toString(total));
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        RF1.setSelected(false);
        SRF1.setSelected(false);
        RCF1.setSelected(false);
        RCF2.setSelected(false);
        SRF1.setSelected(false);
        HAM1.setSelected(false);
        HAMF.setSelected(false);
        CHE2.setSelected(false);
        COLA.setSelected(false);
        SPRITE.setSelected(false);
        CHOCO.setSelected(false);
        PIE.setSelected(false);
        
        jTextPane1.setText("");
        jTextPane2.setText("");
        jTextPane3.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void RF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RF1ActionPerformed
        // TODO add your handling code here:
  
    }//GEN-LAST:event_RF1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try {
            FileWriter order = new FileWriter("order.txt");
            BufferedWriter order1 = new BufferedWriter(order);
            
            for(int i = 0; i < jTable1.getRowCount(); i++) {
                for(int j = 0; j < jTable1.getColumnCount(); j++){
                    order1.write((String)jTable1.getModel().getValueAt(i, j)+ " ");
                }
                order1.write("\n____________________\n");
            }
            
            order1.close();
        }
        catch(IOException i) {
            i.printStackTrace();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        if(jTextPane1.getText().equals("")||jTextPane2.getText().equals("")||jTextPane3.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Please enter correct data! ");
        }
        else {
            String data[] = {jTextPane1.getText(),jTextPane2.getText(),jTextPane3.getText()};
            
            DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();
            tblModel.addRow(data);
            
            JOptionPane.showMessageDialog(this, "Adding Order to tabel Successful!");
            
            jTextPane1.setText("");
            jTextPane2.setText("");
            jTextPane3.setText("");
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();
        if(jTable1.getSelectedRowCount() == 1){
            String subtotal = jTextPane1.getText();
            String tax = jTextPane2.getText();
            String total = jTextPane3.getText();
            
            tblModel.setValueAt(subtotal, jTable1.getSelectedRow(), 0);
            tblModel.setValueAt(tax, jTable1.getSelectedRow(), 1);
            tblModel.setValueAt(total, jTable1.getSelectedRow(), 2);
            
            JOptionPane.showMessageDialog(this, "Update Successfully!");
        }
        else {
            if(jTable1.getRowCount()==0) {
                JOptionPane.showMessageDialog(this, "Table is Empty");
            }
            else {
                JOptionPane.showMessageDialog(this, "Please select single row to update.");
            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();
        if(jTable1.getSelectedRowCount() == 1){
            tblModel.removeRow(jTable1.getSelectedRow());
        }
        else {
            if(jTable1.getRowCount()==0){
                JOptionPane.showMessageDialog(this, "Table is empty.");
            }
            else {
                JOptionPane.showMessageDialog(this, "Please select row to delete");
            }
        }
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();

        String tblSubTotal = tblModel.getValueAt(jTable1.getSelectedRow(), 0).toString();
        String tblTax = tblModel.getValueAt(jTable1.getSelectedRow(), 1).toString();
        String tblTotal = tblModel.getValueAt(jTable1.getSelectedRow(), 2).toString();

        jTextPane1.setText(tblSubTotal);
        jTextPane2.setText(tblTax);
        jTextPane3.setText(tblTotal);
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton CHE1;
    private javax.swing.JRadioButton CHE2;
    private javax.swing.JRadioButton CHOCO;
    private javax.swing.JRadioButton COLA;
    private javax.swing.JRadioButton HAM1;
    private javax.swing.JRadioButton HAMF;
    private javax.swing.JRadioButton PIE;
    private javax.swing.JRadioButton RCF1;
    private javax.swing.JRadioButton RCF2;
    private javax.swing.JRadioButton RF1;
    private javax.swing.JRadioButton SPRITE;
    private javax.swing.JRadioButton SRF1;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JTextPane jTextPane3;
    // End of variables declaration//GEN-END:variables
}
